tls:
  certificates:
    - certFile: "/etc/traefik/tls/bakos.me.crt"
      keyFile: "/etc/traefik/tls/bakos.me.key"
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/tls/bakos.me.crt"
        keyFile: "/etc/traefik/tls/bakos.me.key"

http:
  routers:
    nomad:
      service: nomad
      rule: Host(`nomad.bakos.me`)
      entrypoints:
        - websecure      
      middlewares:
        - auth@file

    consul:
      service: consul
      rule: Host(`consul.bakos.me`)
      entrypoints:
        - websecure
      middlewares:
        - auth@file   

    pfsense:
      service: pfsense
      rule: Host(`pfsense.bakos.me`)
      entrypoints:
        - websecure
      middlewares:
        - auth@file   

    pve:
      service: pve
      rule: Host(`pve.bakos.me`)
      entrypoints:
        - websecure
      middlewares:
        - auth@file   

    pve-backup:
      service: pve-backup
      rule: Host(`pve-backup.bakos.me`)
      entrypoints:
        - websecure
      middlewares:
        - auth@file   

  middlewares:
    auth:
      forwardAuth:
        address: http://auth.service.consul:4181
        authResponseHeaders:
          - X-Forwarded-User
        trustForwardHeader: true

  services:
    nomad:
      loadbalancer:
        servers:
          - url: http://server01.bakos.lan:4646
          - url: http://server02.bakos.lan:4646
          - url: http://server03.bakos.lan:4646                    

    consul:
      loadbalancer:
        servers:
          - url: http://server01.bakos.lan:8500
          - url: http://server02.bakos.lan:8500
          - url: http://server03.bakos.lan:8500

    pfsense:
      loadbalancer:
        servers:
          - url: https://192.168.1.1:443
    
    pve:
      loadbalancer:
        servers:
          - url: https://192.168.1.10:8006
          - url: https://192.168.1.11:8006
          - url: https://192.168.1.12:8006


    pve-backup:
      loadbalancer:
        servers:
          - url: https://192.168.1.13:8007
                    