data_dir = "alloc/data/vector/"
[api]
	enabled = true
	address = "0.0.0.0:8686"
	playground = true
[sources.logs]
	type = "docker_logs"
[sinks.out]
	type = "console"
inputs = [ "logs" ]
	encoding.codec = "json"
[sinks.loki]
	type = "loki" 
	inputs = ["logs"] 
	endpoint = "http://loki.service.consul:3100"
	encoding.codec = "json" 
	healthcheck.enabled = true 
	labels.job = "{{ label.com\\.hashicorp\\.nomad\\.job_name }}"
	labels.group = "{{ label.com\\.hashicorp\\.nomad\\.task_group_name }}"
	labels.task = "{{ label.com\\.hashicorp\\.nomad\\.task_name }}"
	labels.namespace = "{{ label.com\\.hashicorp\\.nomad\\.namespace }}"
	labels.node = "{{ label.com\\.hashicorp\\.nomad\\.node_name }}"
	remove_label_fields = true