job "nfs-node-plugin" {
	type = "system"

	group "nfs-node-plugin" {

		task "nfs-node-plugin" {
  		driver = "docker"

  		config {
		    image = "mcr.microsoft.com/k8s/csi/nfs-csi:latest"
		    privileged = true
  		  args = [
          "--endpoint=unix://csi/csi.sock",
          "--nodeid=${attr.unique.hostname}",
          "--logtostderr",
          "-v=5",
		    ]
  		}

		  csi_plugin {
	    	id        = "nfs"
  		  type      = "node"
  	  	mount_dir = "/csi"
		  }

		  resources {
	  	  memory = 100
  	  	cpu = 200
		  }	
		}
	}
}