- id: '1728520418256'
  alias: 'Lights: exterior lights on at sunset'
  description: Turn on the outside lights each night after sunset
  triggers:
  - event: sunset
    offset: +00:30:00
    trigger: sun
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - switch.front_porch_lights
      - switch.side_door_light
      - switch.back_patio_light
  - wait_for_trigger:
    - trigger: sun
      event: sunrise
      offset: -00:30:00
    continue_on_timeout: false
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - switch.front_porch_lights
      - switch.side_door_light
      - switch.back_patio_light
  mode: single
- id: '1728520859935'
  alias: 'Lights: interior lights on at sunset'
  description: Turn on interior lights prior to sunset
  triggers:
  - event: sunset
    offset: -00:45:00
    trigger: sun
  conditions: []
  actions:
  - action: script.turn_on_evening_lights
    metadata: {}
    data: {}
  - wait_for_trigger:
    - trigger: sun
      event: sunrise
      offset: -00:45:00
    continue_on_timeout: false
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.evening_lights
  mode: single
- id: '1728521120958'
  alias: 'Motion: toggle kitchen lights'
  description: Turn on kitchen lights after dark if motion is detected
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.kitchen_motion
    to: 'on'
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 30
    target:
      entity_id: light.kitchen_lights
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - binary_sensor.kitchen_motion
      to: 'off'
      for:
        hours: 0
        minutes: 10
        seconds: 0
    continue_on_timeout: false
    timeout:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.kitchen_lights
  mode: restart
- id: '1728521312650'
  alias: 'Motion: toggle living room lights'
  description: Turn on living room lights after dark if motion is detected
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.living_room_motion
    to: 'on'
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 25
    target:
      entity_id: light.living_room_lamp
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - binary_sensor.living_room_motion
      to: 'off'
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.living_room_lamp
  mode: restart
- id: '1728521450113'
  alias: 'Motion: toggle stairway lights'
  description: Turn on stairway lights after dark if motion is detected
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.stairway_motion
    to: 'on'
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 25
    target:
      entity_id: light.stairway_lights
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - binary_sensor.stairway_motion
      to: 'off'
    continue_on_timeout: false
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.stairway_lights
  mode: restart
- id: '1728521542519'
  alias: 'Motion: toggle loft lights'
  description: Turn on loft lights after dark if motion is detected
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.loft_motion
    to: 'on'
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 30
    target:
      entity_id: light.loft_lights
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - binary_sensor.loft_motion
      to: 'off'
      for:
        hours: 0
        minutes: 10
        seconds: 0
    continue_on_timeout: false
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.loft_lights
  mode: restart
- id: '1728521658861'
  alias: 'Motion: toggle hall lights'
  description: Turn on hall lights after dark if motion is detected
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.hall_motion
    to: 'on'
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 25
    target:
      entity_id: light.hall_lights
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - binary_sensor.hall_motion
      to: 'off'
    continue_on_timeout: false
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.hall_lights
  mode: restart
- id: '1728522023418'
  alias: 'House: turn on lights when occupied'
  description: Turn on the evening lights if the house has become occupied after sunset
  triggers:
  - trigger: state
    entity_id:
    - cover.garage_door
    to: open
  - trigger: state
    entity_id:
    - person.rich_bakos
    to: home
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  actions:
  - action: script.turn_on_evening_lights
    metadata: {}
    data: {}
  mode: restart
- id: '1728522273863'
  alias: 'Fan: toggle guest bath fan with vanity'
  description: Turn on the bath fan when bathroom is occupied
  triggers:
  - trigger: state
    entity_id:
    - light.guest_bath_vanity
    to: 'on'
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.guest_bath_fan
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - light.guest_bath_vanity
      to: 'off'
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.guest_bath_fan
  mode: single
- id: '1728523914113'
  alias: 'House: shut down when vacant'
  description: Shut down the house when it becomes vacant
  triggers:
  - trigger: state
    entity_id:
    - person.rich_bakos
    to: not_home
    for:
      hours: 0
      minutes: 0
      seconds: 0
  conditions:
  - condition: state
    entity_id: binary_sensor.motion_sensors
    state: 'off'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  actions:
  - action: homeassistant.turn_off
    target:
      area_id:
      - family_room
      - guest_room
      - kitchen
      - laundry
      - living_room
      - loft
      - master_bath
      - nook
      - upstairs
      - master_bedroom
      - water_closet
      entity_id:
      - fan.ceiling_fans
      - switch.fireplace
    data: {}
  mode: single
- id: '1728524358726'
  alias: 'Receiver: set input for Chromecast'
  description: Switch the reciever input to MUSIC when chromecast started to play music
  triggers:
  - trigger: state
    entity_id:
    - media_player.family_room_chromecast
    from: 'off'
  conditions: []
  actions:
  - action: media_player.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: media_player.family_room_tv
  - action: media_player.select_source
    metadata: {}
    data:
      source: MUSIC
    target:
      entity_id: media_player.home_theater
  mode: restart
- id: '1728525357081'
  alias: 'House: turn on fans when occupied'
  description: Turn on the ceiling fans when the house becomes occupied
  triggers:
  - entity_id:
    - person.rich_bakos
    to: home
    trigger: state
  conditions: []
  actions:
  - action: fan.turn_on
    metadata: {}
    data:
      percentage: 15
    target:
      entity_id:
      - fan.ceiling_fans
  mode: restart
- id: '1730526398272'
  alias: 'Motion: toggle family room lights'
  description: Turn on family room lights if motion is detectged after sunset
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.family_room_motion
    to: 'on'
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 25
    target:
      entity_id: light.family_room_lamp
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - binary_sensor.family_room_motion
      to: 'off'
      for:
        hours: 0
        minutes: 10
        seconds: 0
    continue_on_timeout: false
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.family_room_lamp
  mode: restart
- id: '1731980169274'
  alias: 'Fan: sync bedroom fan with switch'
  description: Keep wall switch in sync with Bond fan controller
  use_blueprint:
    path: gist.githubusercontent.com/link_multiple_devices.yaml
    input:
      linked_entities:
      - fan.master_bedroom_fan
      - switch.bedroom_fan_switch
- id: '1731980222440'
  alias: 'Fan: sync family room fan with switch'
  description: Keep wall switch in sync with Bond fan controller
  use_blueprint:
    path: gist.githubusercontent.com/link_multiple_devices.yaml
    input:
      linked_entities:
      - switch.family_room_fan_switch
      - fan.family_room_fan
- id: '1731980290596'
  alias: 'Fan: sync living room fan with switch'
  description: Keep wall switch in sync with Bond fan controller
  use_blueprint:
    path: gist.githubusercontent.com/link_multiple_devices.yaml
    input:
      linked_entities:
      - fan.living_room_fan
      - fan.living_room_fan_switch
- id: '1731984583348'
  alias: 'Garage: light on with door open'
  description: Turn of the garage light as the door opens if I arrive at home after sunset
  triggers:
  - trigger: state
    entity_id:
    - cover.garage_door
    to: open
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.garage_light
  mode: single
- id: '1732076354656'
  alias: 'Fan: toggle nook fan with vanity'
  description: Turn on exhaust fan when bathroom is occupied
  triggers:
  - trigger: state
    entity_id:
    - light.nook_bath_vanity
    to: 'on'
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.nook_bath_fan
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - light.nook_bath_vanity
      to: 'off'
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.nook_bath_fan
  mode: single
- id: '1732076438388'
  alias: 'Fan: toggle water closet fan with water closet light'
  description: Turn on exhaust fan when bathroom is occupied
  triggers:
  - trigger: state
    entity_id:
    - light.water_closet_light
    to: 'on'
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.water_closet_fan
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - light.water_closet_light
      to: 'off'
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.water_closet_fan
  mode: single
