homeassistant:

  # Customization files
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: on

frontend:
config:
system_health:
sun:
dhcp:
zeroconf:
logbook:
stream:
history:

http:
  use_x_forwarded_for: true
  trusted_proxies: !include trusted_proxies.yaml
  ip_ban_enabled: true
  login_attempts_threshold: 5

google_assistant: !include google_assistant.yaml

tts:
  - platform: google_translate

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

light: !include: lights.yaml
switch: !include switch.yaml
cover: !include covers.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
media_player: !include media_players.yaml

