homeassistant:

  # Customization files
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: on

frontend:
config:
system_health:
sun:
dhcp:
zeroconf:
logbook:
stream:
history:

http:
  use_x_forwarded_for: true
  trusted_proxies: !include trusted_proxies.yaml
  ip_ban_enabled: true
  login_attempts_threshold: 5

google_assistant:
  project_id: !secret google_project_id
  service_account: !include service_account.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - fan
    - climate
    - camera
  entity_config:
    switch.garage_door:
      expose: false
    switch.family_room_fan_switch:
      expose: false
    switch.bedroom_fan_switch:
      expose: false
    switch.living_room_fan_switch:
      expose: false

tts:
  - platform: google_translate

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

cover: !include covers.yaml
automation: !include automations.yaml
script: !include scripts.yaml

