- platform: group
  name: Media players
  entities:
    - media_player.family_room_tv
    - media_player.home_theater
    - media_player.sony_xbr_49x900e
    - media_player.bedroom_speaker
    - media_player.bedroom_tv
    - media_player.denon_avr
    - media_player.guest_room_speaker
    - media_player.kitchen_speaker
    - media_player.living_room_speaker
    - media_player.loft_speaker